### ISSUE TITLE
Tidy up WBP Upper Level 

### ISSUE THREAD

**Issue by matentzn** [obophenotype/c-elegans-phenotype-ontology#51]
I noticed that WBls has a lot of floating Life stages. If you open 

http://purl.obolibrary.org/obo/wbls.owl

In Protege, you see 600+ unclassified stages. Maybe move them all under the wbls stage class?

**Comment by chris-grove** [comment]
@matentzn 
Can you tell where that PURL is getting populated from? I'm trying to track that down now. Maybe @raymond91125 knows? I will clean it up ASAP

**Comment by matentzn** [comment]
@chris-grove Oh, this is still hosted at Berkley ontology repo. I can set up a Github repo for you to manage this if we can find the maintainer of the source files. Someone on WormBase must know..

**Comment by raymond91125** [comment]
I believe source file is here <https://github.com/draciti/Life-stage-obo>.

**Comment by chris-grove** [comment]
@matentzn 
Yes, @raymond91125 points to the correct source:

https://github.com/draciti/Life-stage-obo

I think @draciti is planning to make changes to the ontology by script on the raw .OBO file and then upload the new .OBO file back to the repository above, when ready.

The issue is that there is a complete partonomy but not a complete class hiearchy. Because life stages that can be considered a "part of" another life stage can also be considered subclasses ("is a" children) of the same term, the intention is to script the addition of subclass/is_a relations to the existing "part of" parent terms. If that seems way off to anyone, please comment. It seems reasonable to me

**Comment by cmungall** [comment]
I wouldn't script this. It's fine for it to be a partonomy with everything inheriting off a generic "life cycle stage". See the uberon stages ontology and also https://github.com/obophenotype/developmental-stage-ontologies cc @ANiknejad

**Comment by cmungall** [comment]
"this is something that should be solved at the UI level" is the eternal refrain of every ontologist every, but really in this case I think this is a UI issue.

I do get this, but it permeates any ontology with a partonomy, if you look at the typical GO graph display, there is a lot of apparent redundancy.

@fbastian had a talk on this at biocurators in 2013, and implemented in owltools a transitive reduction mechanism that makes for a more biologist friendly view (this was for uberon, but generally applicable)

One solution is simply to extract everything below but not including "life stage" for the purposes of existing apps, so that you just see a partonomy

But I think the more general display issue needs fixed. I am confident we can deliver on this in the context of the alliance :-)

**Comment by chris-grove** [comment]
OK thanks!

**Comment by matentzn** [comment]
+1 on what Chris says. Note that OLS for example displays the partonomy hierarchically! It won’t look pretty on the first level under stage, but after that it’s fine.

**Comment by cmungall** [comment]
oh, I was taking as read that all sensible displays do this, I know historically OWL-oriented tools have just showed subClassOf, but all bio apps show part of hierarchically

The issue with any partonomy tree N deep where each member is grouped under a generic class is that you have a Nx2 lattice, which makes N different paths when showing as a tree view:

https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0014863

![image](https://user-images.githubusercontent.com/50745/52670014-6db07e00-2ecc-11e9-86b2-220c2b8a9c6b.png)

**Comment by chris-grove** [comment]
@matentzn 
I think the original underlying issue (orphaned life stage and anatomy classes) has now been addressed. I'll close the ticket. Please reopen if necessary.
